-- MySQL Script generated by MySQL Workbench
-- jue 05 mar 2026 04:09:15 CST
-- Model: Sakila Full    Version: 2.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema gestion_del_fin
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema gestion_del_fin
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `gestion_del_fin` ;
USE `gestion_del_fin` ;

-- -----------------------------------------------------
-- Table `gestion_del_fin`.`system_config`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_del_fin`.`system_config` (
  `id` TINYINT NOT NULL DEFAULT 1 COMMENT 'Always one, singleton row',
  `version` VARCHAR(20) NULL COMMENT 'e.g. \"1.0.0\"',
  `server_time` DATETIME NOT NULL COMMENT 'Central clock for all camps',
  PRIMARY KEY (`id`))
ENGINE = InnoDB
COMMENT = 'General system parameters\n';


-- -----------------------------------------------------
-- Table `gestion_del_fin`.`camps`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_del_fin`.`camps` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Auto-increment PK',
  `name` VARCHAR(100) NOT NULL COMMENT 'Unique camp name',
  `location` VARCHAR(100) NULL,
  `status` ENUM('ACTIVE', 'ABANDONED') NOT NULL DEFAULT 'ACTIVE' COMMENT 'Current camp status. By default \'ACTIVE\'',
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_del_fin`.`roles`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_del_fin`.`roles` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Auto-increment PK',
  `name` VARCHAR(60) NOT NULL COMMENT 'e.g., system_admin | worker | resource_manager | travel_coordinator',
  `description` VARCHAR(255) NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB
COMMENT = 'Roles that can be assigned to users';


-- -----------------------------------------------------
-- Table `gestion_del_fin`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_del_fin`.`users` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Auto-increment PK',
  `camp_id` INT UNSIGNED NOT NULL COMMENT 'FK to user\'s camp',
  `role_id` INT UNSIGNED NOT NULL,
  `username` VARCHAR(60) NOT NULL,
  `password_hash` VARCHAR(255) NOT NULL COMMENT 'bcrypt / argon2 hash',
  `is_active` TINYINT(1) NOT NULL DEFAULT 1 COMMENT 'Users that have some sort of access to the system',
  `last_activity` TIMESTAMP NULL COMMENT 'Used to enforce the 20-min lock (jwt?)',
  `created_at` DATETIME NOT NULL DEFAULT NOW() COMMENT 'Default NOW()',
  PRIMARY KEY (`id`),
  INDEX `fk_users_camp_idx` (`camp_id` ASC),
  INDEX `fk_users_role_idx` (`role_id` ASC),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC),
  CONSTRAINT `fk_camp_id`
    FOREIGN KEY (`camp_id`)
    REFERENCES `gestion_del_fin`.`camps` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_role_id`
    FOREIGN KEY (`role_id`)
    REFERENCES `gestion_del_fin`.`roles` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Survivors';


-- -----------------------------------------------------
-- Table `gestion_del_fin`.`professions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_del_fin`.`professions` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Auto-increment PK',
  `name` VARCHAR(80) NOT NULL COMMENT 'e.g., scout | farmer | guard | engineer | ...',
  `description` TEXT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_del_fin`.`persons`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_del_fin`.`persons` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Auto-increment PK',
  `camp_id` INT UNSIGNED NOT NULL,
  `profession_id` INT UNSIGNED NOT NULL,
  `full_name` VARCHAR(150) NOT NULL,
  `age` TINYINT UNSIGNED NULL,
  `blood_type` VARCHAR(5) NULL COMMENT 'e.g., A+ | B+ | O+ | ...',
  `skills_summary` TEXT NULL COMMENT 'Text field',
  `photo_url` VARCHAR(500) NULL,
  `status` ENUM('SICK', 'HEALTHY', 'INJURED', 'AWAY', 'DEAD') NOT NULL DEFAULT 'HEALTHY' COMMENT 'Default \'HEALTHY\'',
  `admitted_at` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  INDEX `fk_person_camp__id_idx` (`camp_id` ASC),
  INDEX `fk_persons_profession_id_idx` (`profession_id` ASC),
  CONSTRAINT `fk_camp_id`
    FOREIGN KEY (`camp_id`)
    REFERENCES `gestion_del_fin`.`camps` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_profession_id`
    FOREIGN KEY (`profession_id`)
    REFERENCES `gestion_del_fin`.`professions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Also known as survivors';


-- -----------------------------------------------------
-- Table `gestion_del_fin`.`admission_requests`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_del_fin`.`admission_requests` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Auto-increment PK',
  `camp_id` INT UNSIGNED NOT NULL,
  `applicant_name` VARCHAR(150) NOT NULL,
  `applicant_age` TINYINT UNSIGNED NULL,
  `applicant_skills` TEXT NULL,
  `health_notes` TEXT NULL,
  `background_notes` TEXT NULL,
  `photo_url` VARCHAR(255) NULL,
  `ai_decision` ENUM('ACCEPTED', 'PENDING', 'REJECTED') NOT NULL DEFAULT 'PENDING' COMMENT 'Output decision from AI',
  `ai_reasoning` TEXT NULL COMMENT 'Readable AI explaination based on the request\'s information',
  `ai_suggested_profession` VARCHAR(80) NULL COMMENT 'Profession name suggested by AI',
  `reviewed_by` INT UNSIGNED NULL COMMENT 'FK of reviewer (nullable until reviewd)',
  `final_decision` ENUM('ACCEPTED', 'REJECTED', 'PENDING') NOT NULL DEFAULT 'PENDING',
  `reviewed_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  INDEX `fk_admission_request_camp_idx` (`camp_id` ASC),
  INDEX `fk_user_reviewd_by_idx` (`reviewed_by` ASC),
  CONSTRAINT `fk_camp_id`
    FOREIGN KEY (`camp_id`)
    REFERENCES `gestion_del_fin`.`camps` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_reviewed_by`
    FOREIGN KEY (`reviewed_by`)
    REFERENCES `gestion_del_fin`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_del_fin`.`person_status_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_del_fin`.`person_status_log` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Auto-increment PK',
  `person_id` INT UNSIGNED NOT NULL COMMENT 'FK to the person related to the logged status',
  `old_status` VARCHAR(20) NOT NULL,
  `new_status` VARCHAR(45) NOT NULL,
  `reason` TEXT NULL,
  `changed_by` INT UNSIGNED NOT NULL,
  `changed_at` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  INDEX `fk_person_id_idx` (`person_id` ASC),
  INDEX `fk_changed_by_idx` (`changed_by` ASC),
  CONSTRAINT `fk_person_id`
    FOREIGN KEY (`person_id`)
    REFERENCES `gestion_del_fin`.`persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_changed_by`
    FOREIGN KEY (`changed_by`)
    REFERENCES `gestion_del_fin`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_del_fin`.`profession_reassignment_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_del_fin`.`profession_reassignment_log` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Auto-increment PK',
  `person_id` INT UNSIGNED NOT NULL,
  `from_profession_id` INT UNSIGNED NOT NULL,
  `to_profession_id` INT UNSIGNED NOT NULL,
  `reason` TEXT NULL,
  `start_date` DATE NOT NULL DEFAULT NOW(),
  `end_date` DATE NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_person_id_idx` (`person_id` ASC),
  INDEX `fk_from_profession_id_idx` (`from_profession_id` ASC),
  INDEX `fk_to_profession_id_idx` (`to_profession_id` ASC),
  CONSTRAINT `fk_person_id`
    FOREIGN KEY (`person_id`)
    REFERENCES `gestion_del_fin`.`persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_from_profession_id`
    FOREIGN KEY (`from_profession_id`)
    REFERENCES `gestion_del_fin`.`professions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_to_profession_id`
    FOREIGN KEY (`to_profession_id`)
    REFERENCES `gestion_del_fin`.`professions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_del_fin`.`resource_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_del_fin`.`resource_type` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Auto-increment PK',
  `name` VARCHAR(80) NOT NULL COMMENT 'e.g., meat loaf | food | water | hygiene | medicine | ...',
  `unit` VARCHAR(20) NOT NULL COMMENT 'e.g., kg | liters | lb',
  `daily_ration` DECIMAL(8,2) UNSIGNED NOT NULL COMMENT 'Daily consumption per person',
  `minimum_stock` DECIMAL(10,2) UNSIGNED NOT NULL,
  `auto_daily` TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_del_fin`.`inventory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_del_fin`.`inventory` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Auto-increment PK',
  `camp_id` INT UNSIGNED NOT NULL,
  `resource_type_id` INT UNSIGNED NOT NULL,
  `quantity` DECIMAL(12,2) UNSIGNED NOT NULL DEFAULT 0.00 COMMENT 'Current total',
  `last_updated` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  INDEX `fk_camp_idx` (`camp_id` ASC),
  INDEX `fk_resource_type_idx` (`resource_type_id` ASC),
  UNIQUE INDEX `uq_camp_resource` (`camp_id` ASC, `resource_type_id` ASC),
  CONSTRAINT `fk_camp_id`
    FOREIGN KEY (`camp_id`)
    REFERENCES `gestion_del_fin`.`camps` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resource_type_id`
    FOREIGN KEY (`resource_type_id`)
    REFERENCES `gestion_del_fin`.`resource_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_del_fin`.`inventory_log`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_del_fin`.`inventory_log` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Auto-increment PK\n',
  `camp_id` INT UNSIGNED NOT NULL COMMENT 'Camp related to the log',
  `resource_type_id` INT UNSIGNED NOT NULL,
  `logged_by` INT UNSIGNED NULL COMMENT 'NULLABLE because of possible automated inventory logs',
  `log_type` ENUM('DAILY_GAIN', 'DAILY_RATION', 'MANUAL_IN', 'MANUAL_OUT', 'EXPEDITION_OUT', 'EXPEDITION_IN', 'TRANSFER_OUT', 'TRANSFER_IN') NOT NULL COMMENT 'e.g.: \'DAILY_GAIN\',\'DAILY_RATION\',\'MANUAL_IN\',\'MANUAL_OUT\',\'EXPEDITION_OUT\',\'EXPEDITION_IN\',\'TRANSFER_OUT\',\'TRANSFER_IN\'',
  `delta` DECIMAL(12,2) NOT NULL COMMENT '+ = stock in   − = stock out',
  `logged_at` DATETIME NOT NULL DEFAULT NOW(),
  `description` VARCHAR(255) NULL COMMENT 'Max 255 chars for reduced log descriptions',
  PRIMARY KEY (`id`),
  INDEX `fk_camp__id_idx` (`camp_id` ASC),
  INDEX `fk_resource_id_idx` (`resource_type_id` ASC),
  INDEX `fk_logged_by_idx` (`logged_by` ASC),
  CONSTRAINT `fk_camp_id`
    FOREIGN KEY (`camp_id`)
    REFERENCES `gestion_del_fin`.`camps` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resource_type_id`
    FOREIGN KEY (`resource_type_id`)
    REFERENCES `gestion_del_fin`.`resource_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_logged_by`
    FOREIGN KEY (`logged_by`)
    REFERENCES `gestion_del_fin`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_del_fin`.`contribution_overrides`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_del_fin`.`contribution_overrides` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Auto-increment PK',
  `person_id` INT UNSIGNED NOT NULL,
  `resource_type_id` INT UNSIGNED NOT NULL,
  `reason` VARCHAR(255) NOT NULL,
  `start_date` DATE NOT NULL DEFAULT NOW(),
  `end_date` DATE NULL,
  `created_by` INT UNSIGNED NOT NULL,
  `amount` DECIMAL(8,2) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_person_id_idx` (`person_id` ASC),
  INDEX `fk_resource_type__id_idx` (`resource_type_id` ASC),
  INDEX `fk_created_by_idx` (`created_by` ASC),
  CONSTRAINT `fk_person_id`
    FOREIGN KEY (`person_id`)
    REFERENCES `gestion_del_fin`.`persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resource_type_id`
    FOREIGN KEY (`resource_type_id`)
    REFERENCES `gestion_del_fin`.`resource_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_created_by`
    FOREIGN KEY (`created_by`)
    REFERENCES `gestion_del_fin`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = 'Overrides profession-defined contribution amounts';


-- -----------------------------------------------------
-- Table `gestion_del_fin`.`expeditions`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_del_fin`.`expeditions` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Auto-increment PK',
  `camp_id` INT UNSIGNED NOT NULL,
  `destination` VARCHAR(255) NOT NULL,
  `status` ENUM('PLANNED', 'ONGOING', 'RETURNED', 'CANCELLED') NOT NULL DEFAULT 'PLANNED' COMMENT 'e.g.: \'PLANNED\',\'ONGOING\',\'RETURNED\',\'CANCELLED\'',
  `created_by` INT UNSIGNED NOT NULL,
  `departure_date` DATE NOT NULL,
  `expected_return_date` DATE NOT NULL COMMENT 'Expected but not actually max return date',
  `actual_return_date` DATE NULL,
  `max_return_date` DATE NOT NULL COMMENT 'Buffer from expected return date',
  `notes` TEXT NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  INDEX `fk_camp_id_idx` (`camp_id` ASC),
  INDEX `fk_created_by_idx` (`created_by` ASC),
  CONSTRAINT `fk_camp_id`
    FOREIGN KEY (`camp_id`)
    REFERENCES `gestion_del_fin`.`camps` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_created_by`
    FOREIGN KEY (`created_by`)
    REFERENCES `gestion_del_fin`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_del_fin`.`professions_resources_amounts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_del_fin`.`professions_resources_amounts` (
  `professions_id` INT UNSIGNED NOT NULL,
  `resource_type_id` INT UNSIGNED NOT NULL,
  `amount` DECIMAL(12,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`professions_id`, `resource_type_id`),
  INDEX `fk_resource_type_id_idx` (`resource_type_id` ASC),
  INDEX `fk_profession_type_id_idx` (`professions_id` ASC),
  CONSTRAINT `fk_profession_id`
    FOREIGN KEY (`professions_id`)
    REFERENCES `gestion_del_fin`.`professions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resource_type_id`
    FOREIGN KEY (`resource_type_id`)
    REFERENCES `gestion_del_fin`.`resource_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_del_fin`.`expedition_allocated_resources`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_del_fin`.`expedition_allocated_resources` (
  `expedition_id` INT UNSIGNED NOT NULL,
  `resource_type_id` INT UNSIGNED NOT NULL,
  `amount` DECIMAL(12,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`expedition_id`, `resource_type_id`),
  INDEX `fk_resource_type_id_idx` (`resource_type_id` ASC),
  INDEX `fk_expedition_id_idx` (`expedition_id` ASC),
  CONSTRAINT `fk_expedition_id`
    FOREIGN KEY (`expedition_id`)
    REFERENCES `gestion_del_fin`.`expeditions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resource_type_id`
    FOREIGN KEY (`resource_type_id`)
    REFERENCES `gestion_del_fin`.`resource_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_del_fin`.`expedition_found_resources`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_del_fin`.`expedition_found_resources` (
  `expedition_id` INT UNSIGNED NOT NULL,
  `resource_type_id` INT UNSIGNED NOT NULL,
  `amount` DECIMAL(12,2) UNSIGNED NOT NULL,
  PRIMARY KEY (`expedition_id`, `resource_type_id`),
  INDEX `fk_resource_type_id_idx` (`resource_type_id` ASC),
  INDEX `fk_expedition_id_idx` (`expedition_id` ASC),
  CONSTRAINT `fk_expedition_id`
    FOREIGN KEY (`expedition_id`)
    REFERENCES `gestion_del_fin`.`expeditions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resource_type_id`
    FOREIGN KEY (`resource_type_id`)
    REFERENCES `gestion_del_fin`.`resource_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_del_fin`.`expedition_members`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_del_fin`.`expedition_members` (
  `expedition_id` INT UNSIGNED NOT NULL,
  `person_id` INT UNSIGNED NOT NULL,
  INDEX `fk_expedition_id_idx` (`expedition_id` ASC),
  INDEX `fk_person_id_idx` (`person_id` ASC),
  PRIMARY KEY (`person_id`, `expedition_id`),
  CONSTRAINT `fk_expedition_id`
    FOREIGN KEY (`expedition_id`)
    REFERENCES `gestion_del_fin`.`expeditions` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_id`
    FOREIGN KEY (`person_id`)
    REFERENCES `gestion_del_fin`.`persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_del_fin`.`camp_transfers`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_del_fin`.`camp_transfers` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Auto-increment PK\n',
  `requesting_camp` INT UNSIGNED NOT NULL,
  `target_camp` INT UNSIGNED NOT NULL,
  `status` ENUM('PENDING', 'APPROVED_SOURCE', 'APPROVED_TARGET', 'COMPLETED', 'REJECTED') NOT NULL DEFAULT 'PENDING',
  `type` ENUM('RESOURCE', 'PERSON', 'MIXED') NOT NULL,
  `notes` TEXT NULL,
  `requested_by` INT UNSIGNED NOT NULL,
  `approved_by_source` INT UNSIGNED NULL,
  `approved_by_target` INT UNSIGNED NULL,
  `approved_source_at` DATETIME NULL,
  `approved_target_at` DATETIME NULL,
  `created_at` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  INDEX `fk_requesting_camp_idx` (`requesting_camp` ASC),
  INDEX `fk_target_camp_idx` (`target_camp` ASC),
  INDEX `fk_requested_by_idx` (`requested_by` ASC),
  INDEX `fk_approved_by_source_idx` (`approved_by_source` ASC),
  INDEX `fk_approved_by_target_idx` (`approved_by_target` ASC),
  CONSTRAINT `fk_requesting_camp`
    FOREIGN KEY (`requesting_camp`)
    REFERENCES `gestion_del_fin`.`camps` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_target_camp`
    FOREIGN KEY (`target_camp`)
    REFERENCES `gestion_del_fin`.`camps` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_requested_by`
    FOREIGN KEY (`requested_by`)
    REFERENCES `gestion_del_fin`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_approved_by_source`
    FOREIGN KEY (`approved_by_source`)
    REFERENCES `gestion_del_fin`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_approved_by_target`
    FOREIGN KEY (`approved_by_target`)
    REFERENCES `gestion_del_fin`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_del_fin`.`camp_transfer_item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_del_fin`.`camp_transfer_item` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `camp_transfer_id` INT UNSIGNED NOT NULL,
  `item_type` ENUM('RESOURCE', 'PERSON') NOT NULL,
  `resource_type_id` INT UNSIGNED NULL COMMENT 'If NULL then its person item type',
  `person_id` INT UNSIGNED NULL COMMENT 'If null then its resource item type\n',
  `quantity` DECIMAL(10,2) UNSIGNED NULL COMMENT 'If NULL then is person item type',
  PRIMARY KEY (`id`),
  INDEX `fk_camp_transfer_id_idx` (`camp_transfer_id` ASC),
  INDEX `fk_resource_type_id_idx` (`resource_type_id` ASC),
  INDEX `fk_person_id_idx` (`person_id` ASC),
  CONSTRAINT `fk_camp_transfer_id`
    FOREIGN KEY (`camp_transfer_id`)
    REFERENCES `gestion_del_fin`.`camp_transfers` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_resource_type_id`
    FOREIGN KEY (`resource_type_id`)
    REFERENCES `gestion_del_fin`.`resource_type` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_person_id`
    FOREIGN KEY (`person_id`)
    REFERENCES `gestion_del_fin`.`persons` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_del_fin`.`achievements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_del_fin`.`achievements` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Auto-increment PK.',
  `name` VARCHAR(100) NOT NULL,
  `description` VARCHAR(255) NULL,
  `icon_url` VARCHAR(500) NOT NULL,
  `trigger_rule` VARCHAR(100) NOT NULL COMMENT 'e.g., first_expedition_returned',
  PRIMARY KEY (`id`),
  UNIQUE INDEX `name_UNIQUE` (`name` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `gestion_del_fin`.`user_achievements`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `gestion_del_fin`.`user_achievements` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `user_id` INT UNSIGNED NOT NULL,
  `achievement_id` INT UNSIGNED NOT NULL,
  `earned_at` DATETIME NOT NULL DEFAULT NOW(),
  PRIMARY KEY (`id`),
  INDEX `fk_user_id_idx` (`user_id` ASC),
  INDEX `fk_achivement_id_idx` (`achievement_id` ASC),
  CONSTRAINT `fk_user_id`
    FOREIGN KEY (`user_id`)
    REFERENCES `gestion_del_fin`.`users` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_achivement_id`
    FOREIGN KEY (`achievement_id`)
    REFERENCES `gestion_del_fin`.`achievements` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
